package app.game;

/**
 * Created by Phaethon on 28-Jan-17
 */
public enum RaceType {
    Amoeba("Amoeba_(FFG)","/Base/Amoeba_(FFG).jpg"),
    Anti_Matter("Anti-Matter_(FFG)","/Base/Anti-Matter_(FFG).jpg"),
    Barbarian("Barbarian_(FFG)","/Base/Barbarian_(FFG).jpg"),
    Calculator("Calculator_(FFG)","/Base/Calculator_(FFG).jpg"),
    Chosen("Chosen_(FFG)","/Base/Chosen_(FFG).jpg"),
    Citadel("Citadel_(FFG)","/Base/Citadel_(FFG).jpg"),
    Clone("Clone_(FFG)","/Base/Clone_(FFG).jpg"),
    Cudgel("Cudgel_(FFG)","/Base/Cudgel_(FFG).jpg"),
    Dictator("Dictator_(FFG)","/Base/Dictator_(FFG).jpg"),
    Fido("Fido_(FFG)","/Base/Fido_(FFG).jpg"),
    Filch("Filch_(FFG)","/Base/Filch_(FFG).jpg"),
    Fodder("Fodder_(FFG)","/Base/Fodder_(FFG).jpg"),
    Gambler("Gambler_(FFG)","/Base/Gambler_(FFG).jpg"),
    Grudge("Grudge_(FFG)","/Base/Grudge_(FFG).jpg"),
    Hacker("Hacker_(FFG)","/Base/Hacker_(FFG).jpg"),
    Hate("Hate_(FFG)","/Base/Hate_(FFG).jpg"),
    Healer("Healer_(FFG)","/Base/Healer_(FFG).jpg"),
    Human("Human_(FFG)","/Base/Human_(FFG).jpg"),
    Kamikaze("Kamikaze_(FFG)","/Base/Kamikaze_(FFG).jpg"),
    Loser("Loser_(FFG)","/Base/Loser_(FFG).jpg"),
    Machine("Machine_(FFG)","/Base/Machine_(FFG).jpg"),
    Macron("Macron_(FFG)","/Base/Macron_(FFG).jpg"),
    Masochist("Masochist_(FFG)","/Base/Masochist_(FFG).jpg"),
    Mind("Mind_(FFG)","/Base/Mind_(FFG).jpg"),
    Mirror("Mirror_(FFG)","/Base/Mirror_(FFG).jpg"),
    Miser("Miser_(FFG)","/Base/Miser_(FFG).jpg"),
    Mite("Mite_(FFG)","/Base/Mite_(FFG).jpg"),
    Mutant("Mutant_(FFG)","/Base/Mutant_(FFG).jpg"),
    Observer("Observer_(FFG)","/Base/Observer_(FFG).jpg"),
    Oracle("Oracle_(FFG)","/Base/Oracle_(FFG).jpg"),
    Pacifist("Pacifist_(FFG)","/Base/Pacifist_(FFG).jpg"),
    Parasite("Parasite_(FFG)","/Base/Parasite_(FFG).jpg"),
    Philanthropist("Philanthropist_(FFG)","/Base/Philanthropist_(FFG).jpg"),
    Reincarnator("Reincarnator_(FFG)","/Base/Reincarnator_(FFG).jpg"),
    Remora("Remora_(FFG)","/Base/Remora_(FFG).jpg"),
    Reserve("Reserve_(FFG)","/Base/Reserve_(FFG).jpg"),
    Shadow("Shadow_(FFG)","/Base/Shadow_(FFG).jpg"),
    Sorcerer("Sorcerer_(FFG)","/Base/Sorcerer_(FFG).jpg"),
    Spiff("Spiff_(FFG)","/Base/Spiff_(FFG).jpg"),
    Tick_Tock("Tick-Tock_(FFG)","/Base/Tick-Tock_(FFG).jpg"),
    Trader("Trader_(FFG)","/Base/Trader_(FFG).jpg"),
    Tripler("Tripler_(FFG)","/Base/Tripler_(FFG).jpg"),
    Vacuum("Vacuum_(FFG)","/Base/Vacuum_(FFG).jpg"),
    Virus("Virus_(FFG)","/Base/Virus_(FFG).jpg"),
    Void("Void_(FFG)","/Base/Void_(FFG).jpg"),
    Vulch("Vulch_(FFG)","/Base/Vulch_(FFG).jpg"),
    Warpish("Warpish_(FFG)","/Base/Warpish_(FFG).jpg"),
    Warrior("Warrior_(FFG)","/Base/Warrior_(FFG).jpg"),
    Will("Will_(FFG)","/Base/Will_(FFG).jpg"),
    Zombie("Zombie_(FFG)","/Base/Zombie_(FFG).jpg"),
    Animal("Animal","/Cosmic Alliance/Animal.png"),
    Bandit("Bandit","/Cosmic Alliance/Bandit.jpg"),
    butler("butler","/Cosmic Alliance/butler.png"),
    Chrysalis("Chrysalis","/Cosmic Alliance/Chrysalis.jpg"),
    Crystal("Crystal","/Cosmic Alliance/Crystal.jpg"),
    Cyborg("Cyborg","/Cosmic Alliance/Cyborg.png"),
    Extortionist("Extortionist","/Cosmic Alliance/Extortionist.jpg"),
    General("General","/Cosmic Alliance/General.png"),
    Gorgon("Gorgon","/Cosmic Alliance/Gorgon.jpg"),
    Horde("Horde","/Cosmic Alliance/Horde.jpg"),
    Lightning("Lightning","/Cosmic Alliance/Lightning.png"),
    Poison("Poison","/Cosmic Alliance/Poison.png"),
    Pygmy("Pygmy","/Cosmic Alliance/Pygmy.png"),
    Reborn("Reborn","/Cosmic Alliance/Reborn.jpg"),
    Remote("Remote","/Cosmic Alliance/Remote.jpg"),
    Sapient("Sapient","/Cosmic Alliance/Sapient.jpg"),
    Schizoid("Schizoid","/Cosmic Alliance/Schizoid.jpg"),
    Skeptic("Skeptic","/Cosmic Alliance/Skeptic.jpg"),
    Sting("Sting","/Cosmic Alliance/Sting.png"),
    winner("winner","/Cosmic Alliance/winner.png"),
    Cavalry("Cavalry","/Cosmic Conflict/Cavalry.png"),
    Changeling("Changeling","/Cosmic Conflict/Changeling.png"),
    Empath("Empath","/Cosmic Conflict/Empath.png"),
    Filth("Filth","/Cosmic Conflict/Filth.png"),
    Glutton("Glutton","/Cosmic Conflict/Glutton.png"),
    Graviton("Graviton","/Cosmic Conflict/Graviton.png"),
    Industrialist("Industrialist","/Cosmic Conflict/Industrialist.jpg"),
    Invader("Invader","/Cosmic Conflict/Invader.jpg"),
    Lunatic("Lunatic","/Cosmic Conflict/Lunatic.png"),
    Mimic("Mimic","/Cosmic Conflict/Mimic.jpg"),
    Prophet("Prophet","/Cosmic Conflict/Prophet.jpg"),
    Relic("Relic","/Cosmic Conflict/Relic.png"),
    Saboteur("Saboteur","/Cosmic Conflict/Saboteur.png"),
    Sadist("Sadist","/Cosmic Conflict/Sadist.jpg"),
    Siren("Siren","/Cosmic Conflict/Siren.jpg"),
    The_Claw("The Claw","/Cosmic Conflict/The Claw.png"),
    Trickster("Trickster","/Cosmic Conflict/Trickster.png"),
    Visionary("Visionary","/Cosmic Conflict/Visionary.png"),
    Warhawk("Warhawk","/Cosmic Conflict/Warhawk.jpg"),
    Xenophile("Xenophile","/Cosmic Conflict/Xenophile.png"),
    Ace("Ace","/Cosmic Dominion/Ace.png"),
    Alchemist("Alchemist","/Cosmic Dominion/Alchemist.png"),
    Angler("Angler","/Cosmic Dominion/Angler.png"),
    Aristocrat("Aristocrat","/Cosmic Dominion/Aristocrat.png"),
    Bride("Bride","/Cosmic Dominion/Bride.png"),
    Daredevil("Daredevil","/Cosmic Dominion/Daredevil.png"),
    Diplomat("Diplomat","/Cosmic Dominion/Diplomat.png"),
    Doppelganger("Doppelganger","/Cosmic Dominion/Doppelganger.jpg"),
    Engineer("Engineer","/Cosmic Dominion/Engineer.jpg"),
    Explorer("Explorer","/Cosmic Dominion/Explorer.png"),
    Greenhorn("Greenhorn","/Cosmic Dominion/Greenhorn.jpg"),
    Host("Host","/Cosmic Dominion/Host.png"),
    Joker("Joker","/Cosmic Dominion/Joker.jpg"),
    Judge("Judge","/Cosmic Dominion/Judge.png"),
    Laser("Laser","/Cosmic Dominion/Laser.png"),
    Lizard("Lizard","/Cosmic Dominion/Lizard.png"),
    Love("Love","/Cosmic Dominion/Love.png"),
    Mesmer("Mesmer","/Cosmic Dominion/Mesmer.jpg"),
    Mirage("Mirage","/Cosmic Dominion/Mirage.png"),
    Muckraker("Muckraker","/Cosmic Dominion/Muckraker.jpg"),
    Pentaform("Pentaform","/Cosmic Dominion/Pentaform.jpg"),
    Pickpocket("Pickpocket","/Cosmic Dominion/Pickpocket.png"),
    Pirate("Pirate","/Cosmic Dominion/Pirate.png"),
    Quartermaster("Quartermaster","/Cosmic Dominion/Quartermaster.jpg"),
    Reactor("Reactor","/Cosmic Dominion/Reactor.jpg"),
    Tourist("Tourist","/Cosmic Dominion/Tourist.png"),
    Usurper("Usurper","/Cosmic Dominion/Usurper.jpg"),
    Voyager("Voyager","/Cosmic Dominion/Voyager.png"),
    Whirligig("Whirligig","/Cosmic Dominion/Whirligig.png"),
    Yin_Yang("Yin-Yang","/Cosmic Dominion/Yin-Yang.jpg"),
    AI("AI","/Cosmic Eons/AI.png"),
    Alien("Alien","/Cosmic Eons/Alien.jpg"),
    Anarchist("Anarchist","/Cosmic Eons/Anarchist.jpg"),
    Architect("Architect","/Cosmic Eons/Architect.jpg"),
    Assistant("Assistant","/Cosmic Eons/Assistant.jpg"),
    Bleading_Heart("Bleading Heart","/Cosmic Eons/Bleading Heart.png"),
    Cloak("Cloak","/Cosmic Eons/Cloak.jpg"),
    Coward("Coward","/Cosmic Eons/Coward.png"),
    Crusher("Crusher","/Cosmic Eons/Crusher.jpg"),
    Emperor("Emperor","/Cosmic Eons/Emperor.jpg"),
    Evil_Twin("Evil Twin","/Cosmic Eons/Evil Twin.jpg"),
    Fire_Dancer("Fire Dancer","/Cosmic Eons/Fire Dancer.jpg"),
    Hunger("Hunger","/Cosmic Eons/Hunger.png"),
    Hypochondriac("Hypochondriac","/Cosmic Eons/Hypochondriac.jpg"),
    Klutz("Klutz","/Cosmic Eons/Klutz.png"),
    Maven("Maven","/Cosmic Eons/Maven.jpg"),
    Moocher("Moocher","/Cosmic Eons/Moocher.png"),
    Multitude("Multitude","/Cosmic Eons/Multitude.jpg"),
    Nanny("Nanny","/Cosmic Eons/Nanny.jpg"),
    Nightmare("Nightmare","/Cosmic Eons/Nightmare.png"),
    Oligarch("Oligarch","/Cosmic Eons/Oligarch.jpg"),
    Pack_Rat("Pack Rat","/Cosmic Eons/Pack Rat.jpg"),
    Particle("Particle","/Cosmic Eons/Particle.jpg"),
    Peddler("Peddler","/Cosmic Eons/Peddler.jpg"),
    Perfectionist("Perfectionist","/Cosmic Eons/Perfectionist.jpg"),
    Pretender("Pretender","/Cosmic Eons/Pretender.png"),
    Sheriff("Sheriff","/Cosmic Eons/Sheriff.jpg"),
    Surgeon("Surgeon","/Cosmic Eons/Surgeon.jpg"),
    The_Cult("The Cult","/Cosmic Eons/The Cult.jpg"),
    Tortoise("Tortoise","/Cosmic Eons/Tortoise.jpg"),
    Bully("Bully_(FFG)","/Cosmic Incursion/Bully_(FFG).jpg"),
    Chronos("Chronos_(FFG)","/Cosmic Incursion/Chronos_(FFG).jpg"),
    Cryo("Cryo_(FFG)","/Cosmic Incursion/Cryo_(FFG).jpg"),
    Deuce("Deuce_(FFG)","/Cosmic Incursion/Deuce_(FFG).jpg"),
    Disease("Disease_(FFG)","/Cosmic Incursion/Disease_(FFG).jpg"),
    Ethic("Ethic_(FFG)","/Cosmic Incursion/Ethic_(FFG).jpg"),
    Fungus("Fungus_(FFG)","/Cosmic Incursion/Fungus_(FFG).jpg"),
    Fury("Fury_(FFG)","/Cosmic Incursion/Fury_(FFG).jpg"),
    Genius("Genius_(FFG)","/Cosmic Incursion/Genius_(FFG).jpg"),
    Ghoul("Ghoul_(FFG)","/Cosmic Incursion/Ghoul_(FFG).jpg"),
    Guerrilla("Guerrilla_(FFG)","/Cosmic Incursion/Guerrilla_(FFG).jpg"),
    Leviathan("Leviathan_(FFG)","/Cosmic Incursion/Leviathan_(FFG).jpg"),
    Locust("Locust_(FFG)","/Cosmic Incursion/Locust_(FFG).jpg"),
    Magician("Magician_(FFG)","/Cosmic Incursion/Magician_(FFG).jpg"),
    Mercenary("Mercenary_(FFG)","/Cosmic Incursion/Mercenary_(FFG).jpg"),
    Merchant("Merchant_(FFG)","/Cosmic Incursion/Merchant_(FFG).jpg"),
    Plant("Plant_(FFG)","/Cosmic Incursion/Plant_(FFG).jpg"),
    Seeker("Seeker_(FFG)","/Cosmic Incursion/Seeker_(FFG).jpg"),
    Sniveler("Sniveler_(FFG)","/Cosmic Incursion/Sniveler_(FFG).jpg"),
    Symbiote("Symbiote_(FFG)","/Cosmic Incursion/Symbiote_(FFG).jpg"),
    Arcade("Arcade","/Cosmic Storm/Arcade.jpg"),
    Brute("Brute","/Cosmic Storm/Brute.jpg"),
    Bulwark("Bulwark","/Cosmic Storm/Bulwark.png"),
    Converter("Converter","/Cosmic Storm/Converter.jpg"),
    Coordinator("Coordinator","/Cosmic Storm/Coordinator.jpg"),
    Dervish("Dervish","/Cosmic Storm/Dervish.jpg"),
    Grumpus("Grumpus","/Cosmic Storm/Grumpus.jpg"),
    Mouth("Mouth","/Cosmic Storm/Mouth.jpg"),
    Neighbor("Neighbor","/Cosmic Storm/Neighbor.jpg"),
    Outlaw("Outlaw","/Cosmic Storm/Outlaw.jpg"),
    Patriot("Patriot","/Cosmic Storm/Patriot.jpg"),
    Phantasm("Phantasm","/Cosmic Storm/Phantasm.png"),
    Porcupine("Porcupine","/Cosmic Storm/Porcupine.jpg"),
    Roach("Roach","/Cosmic Storm/Roach.jpg"),
    Scavenger("Scavenger","/Cosmic Storm/Scavenger.jpg"),
    Sloth("Sloth","/Cosmic Storm/Sloth.jpg"),
    Sneak("Sneak","/Cosmic Storm/Sneak.jpg"),
    Squee("Squee","/Cosmic Storm/Squee.jpg"),
    Swindler("Swindler","/Cosmic Storm/Swindler.jpg"),
    Sycophant("Sycophant","/Cosmic Storm/Sycophant.jpg"),
    Tide("Tide","/Cosmic Storm/Tide.jpg"),
    Tyrant("Tyrant","/Cosmic Storm/Tyrant.jpg"),
    Vox("Vox","/Cosmic Storm/Vox.jpg"),
    Worm("Worm","/Cosmic Storm/Worm.jpg"),
    Wormhole("Wormhole","/Cosmic Storm/Wormhole.jpg");

    private String raceName;
    private String fileName;

    RaceType(String raceName, String fileName) {
        this.raceName = raceName;
        this.fileName = fileName;
    }

    public String getRaceName() {
        return raceName;
    }

    public String getFileName() {
        return fileName;
    }

    @Override
    public String toString() {
        return raceName;
    }

    public static RaceType getByName(String name) {
        for (RaceType raceType : values()) {
            if (raceType.getRaceName().equals(name)) {
                return raceType;
            }
        }

        return null;
    }
}
